### PR TITLE
Avoid int cast warning when exporting large floats

### LINKED ISSUE #6589: `dataSetAsStringWithData()` raises "float is not representable as int" warning for large floats in data sets
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 13.1.3
| PHP version         | 8.5.0
| Installation Method | Composer

#### Summary

A warning is raised while PHPUnit formats a dataset name through `dataSetAsStringWithData()` when the dataset contains a large float value.

#### Current behavior

PHPUnit raises this warning:

```
The float 9.223372036854776E+18 is not representable as an int, cast occurred
```

Stack trace:

```
Message:  The float 9.223372036854776E+18 is not representable as an int, cast occurred
Location: /path/to/project/vendor/sebastian/exporter/src/Exporter.php:371
#0 /path/to/project/handler.php(15): app_error_handler(2, 'The float 9.223...', '/mnt/ssd1/works...', 371)
#1 /path/to/project/vendor/sebastian/exporter/src/Exporter.php(371): PHPUnit\TextUI\Configuration\BootstrapLoader->{closure:/path/to/project/handler.php:14}(2, 'The float 9.223...', '/mnt/ssd1/works...', 371)
#2 /path/to/project/vendor/sebastian/exporter/src/Exporter.php(299): SebastianBergmann\Exporter\Exporter->exportFloat(9.2233720368548E+18)
#3 /path/to/project/vendor/sebastian/exporter/src/Exporter.php(86): SebastianBergmann\Exporter\Exporter->recursiveExport(9.2233720368548E+18, 0)
#4 /path/to/project/vendor/sebastian/exporter/src/Exporter.php(175): SebastianBergmann\Exporter\Exporter->export(9.2233720368548E+18)
#5 /path/to/project/vendor/sebastian/exporter/src/Exporter.php(279): SebastianBergmann\Exporter\Exporter->shortenedExport(9.2233720368548E+18, 40)
#6 /path/to/project/vendor/sebastian/exporter/src/Exporter.php(106): SebastianBergmann\Exporter\Exporter->shortenedCountedRecursiveExport(Array, Object(SebastianBergmann\RecursionContext\Context), 0, 40)
#7 /path/to/project/vendor/phpunit/phpunit/src/Util/Exporter.php(32): SebastianBergmann\Exporter\Exporter->shortenedRecursiveExport(Array)
#8 /path/to/project/vendor/phpunit/phpunit/src/Framework/TestCase.php(892): PHPUnit\Util\Exporter::shortenedRecursiveExport(Array)
#9 /path/to/project/vendor/phpunit/phpunit/src/Framework/TestCase.php(320): PHPUnit\Framework\TestCase->dataSetAsStringWithData()
#10 /path/to/project/vendor/phpunit/phpunit/src/Framework/TestCase.php(359): PHPUnit\Framework\TestCase->toString()
#11 /path/to/project/vendor/phpunit/phpunit/src/Framework/TestSuite.php(375): PHPUnit\Framework\TestCase->run()
#12 /path/to/project/vendor/phpunit/phpunit/src/Framework/TestSuite.php(375): PHPUnit\Framework\TestSuite->run()
#13 /path/to/project/vendor/phpunit/phpunit/src/Framework/TestSuite.php(375): PHPUnit\Framework\TestSuite->run()
#14 /path/to/project/vendor/phpunit/phpunit/src/TextUI/TestRunner.php(64): PHPUnit\Framework\TestSuite->run()
#15 /path/to/project/vendor/phpunit/phpunit/src/TextUI/Application.php(234): PHPUnit\TextUI\TestRunner->run(Object(PHPUnit\TextUI\Configuration\Configuration), Object(PHPUnit\Runner\ResultCache\DefaultResultCache), Object(PHPUnit\Framework\TestSuite))
#16 /path/to/project/vendor/phpunit/phpunit/phpunit(104): PHPUnit\TextUI\Application->run(Array)
#17 /path/to/project/vendor/bin/phpunit(122): include('/mnt/ssd1/works...')
#18 {main}
```

#### How to reproduce

Run a test that uses a dataset containing a large float value such as:

```
9.223372036854776E+18
```

In my case, the warning is triggered while PHPUnit generates the dataset string for test output.

#### Expected behavior

PHPUnit should not raise a warning when formatting the dataset name for output, even when the dataset contains a large float value.

### PR DESCRIPTION
**Pull request by zonuexe**
resolve https://github.com/sebastianbergmann/phpunit/issues/6589

Large float values used in tests could trigger a runtime warning:

```
stderr: PHP Warning:  The float 9.223372036854776E+18 is not representable as an int, cast occurred in /path/to/project/vendor/sebastian/exporter/src/Exporter.php on line 371
```

This happened because the previous check cast float values to int while deciding whether to append `.0`. Replace that comparison with a simpler string-based check, which avoids the warning and makes the logic easier to follow.

### CODE REVIEW

File: src/Exporter.php [hunk 1]
```diff
@@ -368,7 +367,8 @@ private function exportFloat(float $value): string
 
         ini_set('precision', $precisionBackup);
 
-        if ($value >= PHP_INT_MIN && $value <= PHP_INT_MAX && (string) (int) $value === $valueAsString) {
+        // Add '.0' only if decimals and scientific notation are absent.
+        if (strpbrk($valueAsString, '.E') !== false) {
```
Comment (zonuexe) [inline src/Exporter.php:371]: I corrected the error where the equals sign and inequality sign was reversed.
